#!/usr/bin/env python

# Copyright 2014
# IIJ Innovation Institute Inc. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
# 
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the following
#   disclaimer in the documentation and/or other materials
#   provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY IIJ INNOVATION INSTITUTE INC. ``AS
# IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL IIJ INNOVATION INSTITUTE INC. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.

import getopt
import sys

from fuse import FUSE

from libukai.ukai_config import UKAIConfig
from libukai.ukai_core import UKAI_CONFIG_FILE_DEFAULT
from libukai.ukai_fuse_connector import UKAIFUSE

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print '''Usage %s [-fd] MOUNTPOINT
\t-f: run in foreground.
\t-d: output debug information.''' % sys.argv[0]
        sys.exit(-1)

    fuse_foreground = False
    fuse_debug = False
    fuse_nothreads = False
    config_file = UKAI_CONFIG_FILE_DEFAULT
    (optlist, args) = getopt.getopt(sys.argv[1:], 'fdc:')
    for opt_pair in optlist:
        if opt_pair[0] == '-f':
            fuse_foreground = True
        if opt_pair[0] == '-d':
            fuse_debug = True
        if opt_pair[0] == '-c':
            config_file = opt_pair[1]
    mountpoint = args[0]

    config = UKAIConfig(config_file)
    fuse_options = config.get('fuse_options')
    if (fuse_options is not None
        and 'nothreads' in fuse_options):
        fuse_nothreads = fuse_options['nothreads']

    FUSE(UKAIFUSE(config), mountpoint,
         foreground=fuse_foreground,
         debug=fuse_debug,
         nothreads=fuse_nothreads,
         allow_other=True)
